
// This file has been generated by the GUI designer. Do not modify.
namespace LuaBinding
{
	public partial class InterpreterOptions
	{
		private global::Gtk.Table MainTabel;
		private global::Gtk.Entry Interpreter51;
		private global::Gtk.Entry Interpreter52;
		private global::Gtk.Entry InterpreterDefault;
		private global::Gtk.Entry InterpreterJIT;
		private global::Gtk.Label label4;
		private global::Gtk.Label label5;
		private global::Gtk.Label label6;
		private global::Gtk.Label label7;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LuaBinding.InterpreterOptions
			global::Stetic.BinContainer.Attach (this);
			this.Name = "LuaBinding.InterpreterOptions";
			// Container child LuaBinding.InterpreterOptions.Gtk.Container+ContainerChild
			this.MainTabel = new global::Gtk.Table (((uint)(4)), ((uint)(2)), false);
			this.MainTabel.Name = "MainTabel";
			this.MainTabel.RowSpacing = ((uint)(6));
			this.MainTabel.ColumnSpacing = ((uint)(6));
			// Container child MainTabel.Gtk.Table+TableChild
			this.Interpreter51 = new global::Gtk.Entry ();
			this.Interpreter51.CanFocus = true;
			this.Interpreter51.Name = "Interpreter51";
			this.Interpreter51.IsEditable = true;
			this.Interpreter51.InvisibleChar = '●';
			this.MainTabel.Add (this.Interpreter51);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.MainTabel [this.Interpreter51]));
			w1.TopAttach = ((uint)(1));
			w1.BottomAttach = ((uint)(2));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child MainTabel.Gtk.Table+TableChild
			this.Interpreter52 = new global::Gtk.Entry ();
			this.Interpreter52.CanFocus = true;
			this.Interpreter52.Name = "Interpreter52";
			this.Interpreter52.IsEditable = true;
			this.Interpreter52.InvisibleChar = '●';
			this.MainTabel.Add (this.Interpreter52);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.MainTabel [this.Interpreter52]));
			w2.TopAttach = ((uint)(2));
			w2.BottomAttach = ((uint)(3));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child MainTabel.Gtk.Table+TableChild
			this.InterpreterDefault = new global::Gtk.Entry ();
			this.InterpreterDefault.CanFocus = true;
			this.InterpreterDefault.Name = "InterpreterDefault";
			this.InterpreterDefault.IsEditable = true;
			this.InterpreterDefault.InvisibleChar = '●';
			this.MainTabel.Add (this.InterpreterDefault);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.MainTabel [this.InterpreterDefault]));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child MainTabel.Gtk.Table+TableChild
			this.InterpreterJIT = new global::Gtk.Entry ();
			this.InterpreterJIT.CanFocus = true;
			this.InterpreterJIT.Name = "InterpreterJIT";
			this.InterpreterJIT.IsEditable = true;
			this.InterpreterJIT.InvisibleChar = '●';
			this.MainTabel.Add (this.InterpreterJIT);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.MainTabel [this.InterpreterJIT]));
			w4.TopAttach = ((uint)(3));
			w4.BottomAttach = ((uint)(4));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child MainTabel.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Default interpreter");
			this.MainTabel.Add (this.label4);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.MainTabel [this.label4]));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child MainTabel.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.Xalign = 0F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Lua 5.1 interpreter");
			this.MainTabel.Add (this.label5);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.MainTabel [this.label5]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child MainTabel.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.Xalign = 0F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Lua 5.2 interpreter");
			this.MainTabel.Add (this.label6);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.MainTabel [this.label6]));
			w7.TopAttach = ((uint)(2));
			w7.BottomAttach = ((uint)(3));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child MainTabel.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.Xalign = 0F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("LuaJIT interpreter");
			this.MainTabel.Add (this.label7);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.MainTabel [this.label7]));
			w8.TopAttach = ((uint)(3));
			w8.BottomAttach = ((uint)(4));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.MainTabel);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
